### ISSUE TITLE
Continuos Integration Tool

### ISSUE THREAD

**Issue by guilhermeddf** [NiPfi/WaaS#21]
Does this project use any Continuous Integration Tool? If so, is it online? (TravisCI, CircleCI), or offline tool (Jenkins, Hudson).

**Comment by NiPfi** [comment]
We're using Azure DevOps, Microsofts Cloud CI/CD tool. You can find it via the "Azure Pipelines" badge on top of the readme or by checking out the build success status of an individual commit (the green chackmark)
